### PR TITLE
[FIX] Dismiss server url view on entering correct url

### LINKED ISSUE #636: [BUG] The server url view appears after the loading view even after entering correct url
-  Rocket.Chat.Android app version: 1.0.33-DEBUG
- Device model (or emulator) you're running with: HTC Desire 628 (Physical Device)
- Steps to reproduce:
1. Enter the **correct** server url and press connect button.
2. The server url view appears after the loading view even when correct url is entered which is a bug.

The following gif demonstrates this bug:

login_error

### PR DESCRIPTION
**Pull request by aniketsingh03**
@RocketChat/android

Closes #636 

The server url view was visible after the loading view even after correct url was entered, which has been fixed in this PR.

How I fixed this:
1. Earlier the view was visible everytime the connect button was clicked because the hideLoader() function was called everytime the button was clicked.
2. The use of a boolean variable which made sure that the function was called only when incorrect url was entered, fixed the issue.

### CODE REVIEW

**Comment by aniketsingh03** [comment]
@rafaelks

**Comment by rafaelks** [comment]
@aniketsingh03 This is going to be reviewed soon, thank you!

File: app/src/main/java/chat/rocket/android/fragment/add_server/InputHostnamePresenter.java [hunk 1]
```diff
@@ -15,6 +15,7 @@
 
 public class InputHostnamePresenter extends BasePresenter<InputHostnameContract.View> implements InputHostnameContract.Presenter {
   private final ConnectivityManagerApi connectivityManager;
+  private boolean isValidServerUrl=false;
```
Comment (leonardoaramaki) [inline app/src/main/java/chat/rocket/android/fragment/add_server/InputHostnamePresenter.java]: @aniketsingh03 LGTM
I would just remove this variable assignment to `false` since it's already implicitly set on `InputHostnamePresenter` instantiation.

**Comment by aniketsingh03** [comment]
@leonardoaramaki kindly review this!

File: app/src/main/java/chat/rocket/android/fragment/add_server/InputHostnamePresenter.java (hunk 1 above)
Comment (aniketsingh03) [reply app/src/main/java/chat/rocket/android/fragment/add_server/InputHostnamePresenter.java]: Yeah sure @leonardoaramaki !

Comment (leonardoaramaki) [reply app/src/main/java/chat/rocket/android/fragment/add_server/InputHostnamePresenter.java]: @aniketsingh03 Any updates on this one?

Comment (aniketsingh03) [reply app/src/main/java/chat/rocket/android/fragment/add_server/InputHostnamePresenter.java]: Sorry, I thought you were changing it. I'll make the changes and commit soon @leonardoaramaki!

Comment (leonardoaramaki) [reply app/src/main/java/chat/rocket/android/fragment/add_server/InputHostnamePresenter.java]: No problem! It's always preferred that the person who authored the PR is the one who implement the change request. :+1:

**Comment by aniketsingh03** [comment]
@leonardoaramaki changes done, you can merge now.
