### PR TITLE
fix lost text when turn off then turn on screen

### LINKED ISSUE #256: [BUG] Text in input lost when screen sleeps
Your Rocket.Chat.Android version: latest

I've had several times where I have a big message typed and someone starts talking to me in person.  So I stop typing.  Screen goes to sleep.  Then I wake it and message is gone. 

So right now if its important I have to keep tapping the phone to keep it awake until I can hit send :grin:

### PR DESCRIPTION
**Pull request by congnt24**
fix lost text when turn off then turn on screen, hide keyboard when change room chat

@RocketChat/android

Closes #256

### CODE REVIEW

File: app/src/main/java/chat/rocket/android/activity/MainActivity.java [hunk 1]
```diff
@@ -51,7 +52,7 @@ protected void onCreate(@Nullable Bundle savedInstanceState) {
   @Override
   protected void onPause() {
     if (presenter != null) {
-      presenter.release();
+//      presenter.release();
```
Comment (laggedHero) [inline app/src/main/java/chat/rocket/android/activity/MainActivity.java]: This is really bad since we'll not clean up the subscriptions made. I can't accept this change.

File: app/src/main/java/chat/rocket/android/activity/AbstractAuthedActivity.java [hunk 2]
```diff
@@ -36,6 +36,10 @@ protected void onCreate(@Nullable Bundle savedInstanceState) {
     if (savedInstanceState == null) {
       handleIntent(getIntent());
     }
+    ConnectivityManager.getInstance(getApplicationContext()).keepAliveServer();
```
Comment (laggedHero) [inline app/src/main/java/chat/rocket/android/activity/AbstractAuthedActivity.java]: Let's put this back into the `onResume`. It's trying to keep the connection alive.

**Review by laggedHero — CHANGES_REQUESTED** [review]

**Comment by congnt24** [comment]
The problem is that whenever onResume() call, it will recreate a new RoomFragment and the state of fragment will lose, not just text in EditText. I already changed some code that you requested. Please review.

File: app/src/main/java/chat/rocket/android/activity/MainActivity.java [hunk 3]
```diff
@@ -172,6 +181,8 @@ public void showHome() {
   public void showRoom(String hostname, String roomId) {
     showFragment(RoomFragment.create(hostname, roomId));
     closeSidebarIfNeeded();
+    //TODO: Hide keyboard
+    KeyboardHelper.hideSoftKeyboard(this);
```
Comment (geekgonecrazy) [inline app/src/main/java/chat/rocket/android/activity/MainActivity.java]: Looks like might have a comment that needs removed.  The line right below seems to be doing exactly what the TODO calls for :)

**Comment by laggedHero** [comment]
There's still some rough edges... but the code here, in general, is kind of rough.

Let's remove that comment and merge it in.

**Comment by congnt24** [comment]
I've removed comment

**Review by laggedHero — APPROVED** [review]

**Comment by laggedHero** [comment]
Hmm, I'll check the build here.
