### PR TITLE
[FIX] Fix uppercase url scheme

### LINKED ISSUE #1546: [BUG] Links with uppercase on the scheme are not working
Refer to: https://github.com/RocketChat/Rocket.Chat.Android/pull/967

### PR DESCRIPTION
**Pull request by luciofm**
closes #967 
closes #1546

### CODE REVIEW

File: app/src/main/java/chat/rocket/android/util/extensions/View.kt [hunk 1]
```diff
@@ -7,15 +7,27 @@ import android.view.View
...
         } catch (ex: Exception) {
             Timber.d(ex, "Unable to launch URL")
         }
     }
+}
+
+private fun String.ensureScheme(): Uri? {
+    // check if the URL starts with a http(s) scheme
+    val url = if (!this.matches(Regex("^([h|H][t|T][t|T][p|P]).*"))) {
+        "http://$this"
```
Comment (rafaelks) [inline app/src/main/java/chat/rocket/android/util/extensions/View.kt:27]: What if the scheme is HTTPS?

Comment (luciofm) [reply app/src/main/java/chat/rocket/android/util/extensions/View.kt:27]: This is just to check if the url already has a scheme... Sometimes we receive urls like "www.something.com", so we append "http://"

Comment (rafaelks) [reply app/src/main/java/chat/rocket/android/util/extensions/View.kt:27]: Gotcha! 👍
