### PR TITLE
[WIP][FIX] Chat history sync

### LINKED ISSUE #1353: [BUG] Message history is not always synchronized normally after a long absence
Your Rocket.Chat.Android version: 2.3.0 - 2.4.0
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.4.12) , Developer ROM
Your Rocket.Chat Server version: 0.65.1

Sometimes after a long absence on the channel when I run the chat program on the smartphone, I do not see a pretty large array of message history. They just do not load. This happens almost every day and does not synchronize somewhere around 1 - 1.5 hours of messages. It occurs without any apparent reason. In the web version of chat, all messages are displayed normally.
Web-version:
img_20180612_081320

Android version:
img_20180612_080738

UPD. Today it happened again.

Android version:
img_20180614_091436

Web-version:

img_20180614_091722

### PR DESCRIPTION
**Pull request by luckcoolla**
@RocketChat/android

Closes #1353 #1302 should be checked

I saw that there are some issues with messages synchronization in the chat room during I do turn-off internet and then connects again. Let's check out two described and fixed issues!

**---Issue 1---**
**Steps to Reproduce:**

0. Go to room dialog btw Android client and web-browser client. Turn off internet connection on the android client
1. web-browser client sends the message 
2. Android client written and sends the message
3. Android client connects to the internet
**4. Android client see only own sent messages. web-browser client can see both own and received from Android messages.**

This issue caused by ChatRoomAdapter.kt code (see FIXME message):
screen shot 2018-08-22 at 7 24 50 pm

**---Issue 2---**
**Steps to Reproduce:**

0. Go to room dialog btw Android client and web-browser client. Turn off internet connection on the android client
1. web-browser client sends the message 1
2. Android client written and sends the message 2
3. web-browser client sends the message 3
4. Android client connects to the internet
5. **Open Logcat. Android client asks only for chat history with message 2 and message 3.**

screen shot 2018-08-22 at 7 44 38 pm

Let's me explain more here:
When user tries to send message without internet, the MessageService : JobService has been started by ChatRoomPresenter#sendMessage method. JobService has own retrySendingMessages loop inside.
Plus there is reconnecting loop in the chat room itself. ChatRoomPresenter#subscribeState waits for reconnected state and calls loadMissingMessages.

Both retry loops(for sending and receiving) are working simultaneously and usually we have next scenario:
When user turns on internet All local unsend messages being sent + saved to local database(so the last saved message for the room is our message). This message received and recorded on the Server as the latest one in the room.
After some time loadMissingMessages() method is working and **brings only our last message + messages after our(if any).**  Because loadMissingMessages call only for newest messages at top of the latest saved message.
So all incoming messages from web-client for this no-internet period in Android client are being ignored.

### CODE REVIEW

File: app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt [hunk 1]
```diff
@@ -225,6 +226,15 @@ class ChatRoomPresenter @Inject constructor(
                 client.messages(chatRoomId, roomTypeOf(chatRoomType), offset, 30).result
             }
         messagesRepository.saveAll(messages)
+
+        //if success - saving last synced time
+        if (messages.isEmpty()) {
+            messagesRepository.saveLastSyncDate(System.currentTimeMillis())
```
Comment (luckcoolla) [inline app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt]: we call saveLastSyncDate() inside loadAndShowMessages() method because it's the plain request for the latest chat history

File: app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt [hunk 2]
```diff
@@ -513,6 +529,9 @@ class ChatRoomPresenter @Inject constructor(
                                     isRoom = true
                                 ))
                                 messagesRepository.saveAll(messages.result)
+                                //if success - saving last synced time
+                                // TODO sort and peek the latest date
+                                messagesRepository.saveLastSyncDate(messages.result.last().timestamp)
```
Comment (luckcoolla) [inline app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt]: and we call messagesRepository.saveLastSyncDate() inside loadMissingMessages() because here we again are in the point of chat history synchronization

**Comment by philipbrito** [comment]
Hi @luckcoolla Could you please sign our CLA?
Thanks for your PR!

File: app/src/main/java/chat/rocket/android/server/infraestructure/MemoryMessagesRepository.kt [hunk 3]
```diff
@@ -7,6 +7,14 @@ import kotlinx.coroutines.experimental.withContext
 
 class MemoryMessagesRepository : MessagesRepository {
 
+    private var lastSyncDate: Long? = null
+
+    override suspend fun saveLastSyncDate(it: Long) {
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/server/infraestructure/MemoryMessagesRepository.kt]: It's better to use the same argument name here as defined on the interface: `currentTimeMillis `

File: app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesMessagesRepository.kt [hunk 4]
```diff
@@ -13,6 +13,28 @@ class SharedPreferencesMessagesRepository(
...
+                prefs.edit().putLong(getSyncDateKey(it), currentTimeMillis).apply()
+            }
+        }
+    }
+
+    override suspend fun getLastSyncDate(): Long? = withContext(CommonPool) {
+        currentServerInteractor.get()?.also { server ->
+            if (!prefs.contains(getSyncDateKey(server)))
+                return@withContext null
+            //
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesMessagesRepository.kt]: Is it supposed to be a comment? 
Could you please remove that or update that?

File: app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt [hunk 5]
```diff
@@ -150,23 +150,23 @@ class ChatRoomAdapter(
...
+        val filteredDataSet = dataSet.filter { newItem ->
+            val matchedIndex = this.dataSet.indexOfFirst { it.messageId == newItem.messageId && it.viewType == newItem.viewType }
+            if (matchedIndex > -1) {
+                this.dataSet[matchedIndex] = newItem
+                notifyItemChanged(matchedIndex)
             }
+            return@filter (matchedIndex < 0)
         }
+        //At the second stage we are inserting new received elements into set.
+        if (filteredDataSet.size == 0)
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt]: Could you please put the `return` in the same line of `if (filteredDataSet.size == 0)`

**Review by philipbrito — CHANGES_REQUESTED** [review]

File: app/src/main/java/chat/rocket/android/server/infraestructure/MemoryMessagesRepository.kt (hunk 3 above)
Comment (luckcoolla) [reply app/src/main/java/chat/rocket/android/server/infraestructure/MemoryMessagesRepository.kt]: agree

File: app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesMessagesRepository.kt (hunk 4 above)
Comment (luckcoolla) [reply app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesMessagesRepository.kt]: yep, removed

File: app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt (hunk 5 above)
Comment (luckcoolla) [reply app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt]: sure

**Comment by luckcoolla** [comment]
@filipedelimabrito I've covered all points, recheck please)

**Comment by luckcoolla** [comment]
@filipedelimabrito I've found small issue with unexpected ui behaviour on the attachment file showing.
My changes in ChatRoomAdapter.kt caused it.
I'm gonna fix it in the nearest days, don't merge the PR now please

**Comment by philipbrito** [comment]
Thanks for letting us know @luckcoolla . 👍

**Comment by luckcoolla** [comment]
@filipedelimabrito I've finished changes, now it should be ok in all cases described in this ticket + general messaging cases like quote/reply/attach files.

I caught the main idea that in case of any action like reply/attach/.. UiModelMapper creates several objects: BaseUiModel and then they arrives to ChatRoomAdapter#prependData method.
Just like example if I write new message with reply action, two new message objects are being passed to ChatRoomAdapter#prependData.

In the "#prependData" method I added simple check on new messages time to reduce notifyDataSetChanged() calls 
\+ I added comparison on viewType into the sorting comparator function, so layout on merged chat history should be same as on new messages.

File: app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt [hunk 6]
```diff
@@ -184,7 +184,8 @@ class ChatRoomPresenter @Inject constructor(
                             isBroadcast = chatIsBroadcast, isRoom = true
                         )
                     )
-                    if (oldMessages.isNotEmpty()) {
+                    val lastSyncDate = messagesRepository.getLastSyncDate()
```
Comment (luciofm) [inline app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt]: This value should be per roomId, otherwise we will use the last sync date from other rooms

**Review by luciofm — CHANGES_REQUESTED** [review]

File: app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt (hunk 6 above)
Comment (luckcoolla) [reply app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt]: @luciofm yep, it's my mistake. I've tested on my local branch with one room only.
Gonna fix it

Comment (luckcoolla) [reply app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt]: fixed

File: app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt [hunk 7]
```diff
@@ -483,45 +497,49 @@ class ChatRoomPresenter @Inject constructor(
 
     private fun loadMissingMessages() {
         launch(parent = strategy.jobs) {
-            if (chatRoomId != null && chatRoomType != null) {
```
Comment (luckcoolla) [inline app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt:486]: chatRoomType: String now

**Comment by luckcoolla** [comment]
@luciofm I've finished code changes.

**Review by luciofm — APPROVED** [review]

**Comment by luciofm** [comment]
@luckcoolla we are getting a crash when you call prepend on an empty adapter

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
       at java.util.ArrayList.get(ArrayList.java:437)
       at chat.rocket.android.chatroom.adapter.ChatRoomAdapter.prependData(ChatRoomAdapter.kt:172)
       at chat.rocket.android.chatroom.ui.ChatRoomFragment.showNewMessage(ChatRoomFragment.kt:508)
       at chat.rocket.android.chatroom.presentation.ChatRoomPresenter$loadMissingMessages$1$doResume$$inlined$let$lambda$2.doResume(ChatRoomPresenter.kt:526)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
       at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
       at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6798)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by luckcoolla** [comment]
@luciofm yep, I see

`if (minAdditionDate.message.timestamp > this.dataSet[0].message.timestamp) {`

It's the case when you are connecting to the non-empty room from some new device/app installation.

Should I add commit just here in current branch or to create some new pr to beta?

**Comment by philipbrito** [comment]
Open a new PR fixing that bug if you can @luckcoolla.
Thank you!

**Comment by luckcoolla** [comment]
@filipedelimabrito ok, next time I'll do it in this way)
Now I see @luciofm pushed the crash fix https://github.com/RocketChat/Rocket.Chat.Android/commit/33d3b5f0df0c8fdccb538b3e5d03bdf61a943194
Thanks!
