### PR TITLE
[FEATURE] DB Spotlight + fixes

### LINKED ISSUE #1434: [BUG] Search in the channels list is not working
On the chat screen, type anything on the channel's search input field, nothing happens. Hit the search icon,  still nothing happens.

### PR DESCRIPTION
**Pull request by luciofm**
Spotlight, loading and empty indicators, fixes on rooms synchronization and other fixes

Closes #1434

depends on https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/192

### CODE REVIEW

File: app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomUiModelMapper.kt [hunk 1]
```diff
@@ -48,6 +51,47 @@ class RoomUiModelMapper(
...
+        }
+        spotlight.rooms.filterNot { it.name.isNullOrEmpty() }.forEach { room ->
+            list.add(RoomItemHolder(mapRoom(room)))
+        }
+
+        return list
+    }
+
+    private fun mapUser(user: User): RoomUiModel {
+        return with(user) {
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomUiModelMapper.kt:67]: 👍

File: app/src/main/java/chat/rocket/android/chatrooms/di/ChatRoomsFragmentModule.kt [hunk 2]
```diff
@@ -71,7 +71,8 @@ class ChatRoomsFragmentModule {
 
     @Provides
     @PerFragment
-    fun provideFetchChatRoomsInteractor(client: RocketChatClient, dbManager: DatabaseManager): FetchChatRoomsInteractor {
+    fun provideFetchChatRoomsInteractor(client: RocketChatClient,
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/chatrooms/di/ChatRoomsFragmentModule.kt:74]: Formatting can be improved in the future.

File: app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt [hunk 3]
```diff
@@ -5,51 +5,96 @@ import androidx.lifecycle.MutableLiveData
...
-        return Transformations.switchMap(ordering) { order ->
-            Timber.d("Querying rooms for order: $order")
-            repository.getChatRooms(order)
-                    .nonNull()
-                    .distinct()
-                    .transform(runContext) { rooms ->
-                        rooms?.let {
-                            mapper.map(rooms, order.isGrouped())
-                        }
+                    // debounce, to not query while the user is writing
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt:51]: 👁 👍

File: app/src/main/java/chat/rocket/android/util/livedata/WrappedLiveData.kt [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+import androidx.lifecycle.MutableLiveData
+import androidx.lifecycle.Observer
+import kotlinx.coroutines.experimental.CommonPool
+import kotlinx.coroutines.experimental.CoroutineScope
+import kotlinx.coroutines.experimental.Job
+import kotlinx.coroutines.experimental.android.UI
+import kotlinx.coroutines.experimental.launch
+import kotlinx.coroutines.experimental.withContext
+import kotlin.coroutines.experimental.CoroutineContext
+
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/util/livedata/WrappedLiveData.kt:13]: Unneeded empty line.

File: app/src/main/res/values-es/strings.xml [hunk 5]
```diff
@@ -282,4 +282,5 @@
     <string name="notif_action_reply_hint">RESPUESTA</string>
     <string name="notif_error_sending">La respuesta ha fallado. Inténtalo de nuevo.</string>
     <string name="notif_success_sending">Mensaje enviado a %1$s!</string>
+    <string name="msg_log_out">Saliendo de tu cuenta...</string>
```
Comment (philipbrito) [inline app/src/main/res/values-es/strings.xml:287]: Spanish 🇺🇾 
👌

File: app/src/main/res/values-fr/strings.xml [hunk 6]
```diff
@@ -283,4 +283,5 @@
     <string name="notif_action_reply_hint">RÉPONDRE</string>
     <string name="notif_error_sending">La réponse a échoué. Veuillez réessayer.</string>
     <string name="notif_success_sending">Message envoyé à %1$s!</string>
+    <string name="msg_log_out">Logging out...</string>
```
Comment (philipbrito) [inline app/src/main/res/values-fr/strings.xml:289]: Better to add a TODO indicating that this string needs translation, so the contributors can find the strings to be translated easily.

File: app/src/main/res/values-hi-rIN/strings.xml [hunk 7]
```diff
@@ -260,4 +260,5 @@
     <string name="notif_action_reply_hint">जवाब</string>
     <string name="notif_error_sending">उत्तर विफल हुआ है। कृपया फिर से प्रयास करें।</string>
     <string name="notif_success_sending">संदेश भेजा गया %1$s!</string>
+    <string name="msg_log_out">Logging out...</string>
```
Comment (philipbrito) [inline app/src/main/res/values-hi-rIN/strings.xml:266]: Better to add a TODO indicating that this string needs translation, so the contributors can find the strings to be translated easily.

File: app/src/main/res/values-uk-rRU/strings.xml [hunk 8]
```diff
@@ -257,4 +257,5 @@
     <string name="notif_action_reply_hint">ОТВЕТИТЬ</string>
     <string name="notif_error_sending">Ошибка ответа. Пожалуйста, попробуйте еще раз.</string>
     <string name="notif_success_sending">Сообщение отправлено %1$s!</string>
+    <string name="msg_log_out">Logging out...</string>
```
Comment (philipbrito) [inline app/src/main/res/values-uk-rRU/strings.xml:263]: Better to add a TODO indicating that this string needs translation, so the contributors can find the strings to be translated easily.

**Review by philipbrito — APPROVED** [review]
