### PR TITLE
[FIX] Layout improvements

### LINKED ISSUE #751: [IMPROVEMENT] Size of the elements, spacing & colors
- [x] Reduce size of the font of the chats screen to something very similar to Telegram;
- [x] Reduce size of the font of the messages screen to something very similar to Telegram; Make the same font size as the text box;
- [x] Change color of mentions on reply/quote banner to something a blue lighter. Right now is almost impossible to read it;
- [x] Use different font style for read/unread channels on the chats list; Here you can use bold in the name of the channel when there's any unread message and change the date label color to the same blue we have in the "unread bubble" and if the chat has no unread messages you simply use semi-bold font and the same color you're using today for date on the date label;
- [x] Change animation to open/close an activity to something faster (see how Telegram is doing);
- [x] Support dragging from left to right to close messages activity;

### PR DESCRIPTION
**Pull request by philipbrito**
Closes #751 

photo_2018-02-23_11-38-38

photo_2018-02-23_11-38-41

### CODE REVIEW

**Comment by luciofm** [comment]
@filipedelimabrito can you add some screenshots please.

File: app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt [hunk 1]
```diff
@@ -105,23 +96,14 @@ class ChatRoomsFragment : Fragment(), ChatRoomsView {
...
-
     private fun setupToolbar() {
         (activity as AppCompatActivity).supportActionBar?.title = getString(R.string.title_chats)
     }
 
     private fun setupRecyclerView() {
         activity?.apply {
             recycler_view.layoutManager = LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false)
-            recycler_view.addItemDecoration(DividerItemDecoration(this, 144, 32))
+            recycler_view.addItemDecoration(DividerItemDecoration(this, 144, 0))
```
Comment (luciofm) [inline app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt]: We should use dimensions on dimens.xml in DPs

File: app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+import chat.rocket.common.RocketChatException
+import chat.rocket.core.RocketChatClient
+import chat.rocket.core.internal.realtime.disconnect
+import chat.rocket.core.internal.rest.logout
+import chat.rocket.core.internal.rest.unregisterPushToken
+import timber.log.Timber
+import javax.inject.Inject
+
+class MainPresenter @Inject constructor(
+
```
Comment (luciofm) [inline app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt]: Remove this empty line
