### PR TITLE
[FIX] Send button goes MIA while new message arrives

### LINKED ISSUE #1892: Message sending button disappears
Your Rocket.Chat.Android version: 3.2.0 Build 2051 - e51c8da7 - play
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.71.1

When you type a message and someone sends a message to the channel, message sending button disappears.

img_20181201_183046

### PR DESCRIPTION
**Pull request by leonardoaramaki**
@RocketChat/android

Closes #1892

### CODE REVIEW

File: app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt [hunk 1]
```diff
@@ -862,7 +858,6 @@ class ChatRoomFragment : Fragment(), ChatRoomView, EmojiKeyboardListener, EmojiR
             )
 
             subscribeComposeTextMessage()
-            getUnfinishedMessage()
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt:862]: Will the user be able to see its unfinished message after this removed function?

Comment (leonardoaramaki) [reply app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt:862]: No, I should have pointed this out on the description. It's on the commit message only.
This feature is not working properly, so I thought it would be better to temporarily disable this feature until we get to fix it.

**Review by rafaelks — APPROVED** [review]
LGTM.
