### PR TITLE
[FIX] Listen to favorite changes

### LINKED ISSUE #2234: [BUG] Channel Details view is not showing that a channel is favorite
When opening the Channel Details view the favorite icon isn't working as expected. It should show the favorite icon when a channel is starred from the user.

### PR DESCRIPTION
**Pull request by Adizbek**
@RocketChat/android

Closes #2234

### CODE REVIEW

File: app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt [hunk 1]
```diff
@@ -463,6 +464,7 @@ class ChatRoomFragment : Fragment(), ChatRoomView, EmojiKeyboardListener, EmojiR
             setupToolbar(roomUiModel.name.toString())
             setupMessageComposer(roomUiModel)
             isBroadcastChannel = roomUiModel.broadcast
+            isFavorite = roomUiModel.favorite.orFalse()
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt:467]: 👏

**Review by philipbrito — APPROVED** [review]
