### PR TITLE
[FIX] Improvements on the chatrooms list

### LINKED ISSUE #1506: [IMPROVEMENT] Improvements to room list last messages
## Description

The room list is showing different (and not clever) information regarding the last message as on desktop. 

## Devices and Versions

Your Rocket.Chat.Android version: 2.5.0
Your Rocket.Chat Server version: open server

Mobile device model and OS version: Moto Maxx

## Steps to reproduce

Just open the app and look at your rooms list:

* If the last message is a file upload, it shows just the username. On desktop it shows "Sent an attachment"
* If the last message was sent by me it shows my **name** (to everyone else it shows the username). On desktop it shows `You` (which I think is the best/common approach).
* On direct messages it shows either my name or the open person's username. As on desktop it just needs to show either `You` (which is me 😅 ) or just the message, because I know if it wasn't sent by me it was sent by the other person on DM)

The image bellow shows all three items:
image

### PR DESCRIPTION
**Pull request by luciofm**
depends on https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/195

Closes #1506

### CODE REVIEW

File: app/src/main/java/chat/rocket/android/db/DatabaseManager.kt [hunk 1]
```diff
@@ -313,7 +409,7 @@ class DatabaseManager(val context: Application,
         }
     }
 
-    fun findUser(userId: String?): String? = if (userId != null) userDao().findUser(userId) else null
+    fun findUser(userId: String): String? = userDao().findUser(userId)
 }
 
 fun User.toEntity(): BaseUserEntity? {
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/db/DatabaseManager.kt:421]: We need this?

**Review by philipbrito — APPROVED** [review]

**Review by rafaelks — APPROVED** [review]
Looking really good! 👍
