### PR TITLE
[BUG] Empty file view

### LINKED ISSUE #1347: [BUG] Empty file view
device-2018-06-07-133302

### PR DESCRIPTION
**Pull request by divyanshub024**
@RocketChat/android

Closes #1347 

device-2018-06-07-135355

### CODE REVIEW

File: app/src/main/java/chat/rocket/android/files/ui/FilesFragment.kt [hunk 1]
```diff
@@ -86,6 +86,7 @@ class FilesFragment : Fragment(), FilesView {
                     }
                 })
             }
+            group_no_file.isVisible = dataSet.isEmpty()
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/files/ui/FilesFragment.kt:89]: Good catch @divyanshub024!

Thank you very much!

**Review by philipbrito — APPROVED** [review]

File: app/src/main/java/chat/rocket/android/files/ui/FilesFragment.kt (hunk 1 above)
Comment (divyanshub024) [reply app/src/main/java/chat/rocket/android/files/ui/FilesFragment.kt:89]: :+1:
