### PR TITLE
[BUG] Check and Request camera permission before taking photos.

### LINKED ISSUE #2197: [BUG] App is crashing while taking photos without permission
## Describe the bug

App is crashing while taking photos from camera without camera permission.

## Logs
```
    Process: chat.rocket.android.dev, PID: 7587
    java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=org.codeaurora.snapcam/com.android.camera.PermissionsActivity clip={text/uri-list U:content://chat.rocket.android.fileprovider/rocket_chat_images/PNG_20190404_225545_3747566536821672278.png} (has extras) } from ProcessRecord{6bfe80 7587:chat.rocket.android.dev/u0a325} (pid=7587, uid=10325) with revoked permission android.permission.CAMERA
        at android.os.Parcel.readException(Parcel.java:2013)
        at android.os.Parcel.readException(Parcel.java:1959)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4352)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1613)
        at android.app.Activity.startActivityForResult(Activity.java:4501)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:886)
        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:995)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1103)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1092)
        at chat.rocket.android.chatroom.ui.ChatRoomFragment.dispatchTakePictureIntent(ChatRoomFragment.kt:964)
        at chat.rocket.android.chatroom.ui.ChatRoomFragment.access$dispatchTakePictureIntent(ChatRoomFragment.kt:144)
        at chat.rocket.android.chatroom.ui.ChatRoomFragment$setupMessageComposer$8.onClick(ChatRoomFragment.kt:909)
        at android.view.View.performClick(View.java:6302)
        at android.view.View$PerformClick.run(View.java:24782)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

### PR DESCRIPTION
**Pull request by divyanshub024**
@RocketChat/android

Closes #2197

### CODE REVIEW

File: app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt [hunk 1]
```diff
@@ -957,6 +966,33 @@ class ChatRoomFragment : Fragment(), ChatRoomView, EmojiKeyboardListener, EmojiR
         }
     }
 
+    private fun hasCameraPermission(context: Context): Boolean {
+        return AndroidPermissionsHelper.checkPermission(context, android.Manifest.permission.CAMERA)
+    }
+
+    private fun getCameraPermission() {
+        requestPermissions(
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt]: The same way you did above, you could did here. 

Use `AndroidPermissionsHelper.requestPermission(...)`

or, I'd move it to `AndroidPermissionsHelper` class in order to centralize all the permissions stuffs.

File: app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt [hunk 2]
```diff
@@ -957,6 +966,33 @@ class ChatRoomFragment : Fragment(), ChatRoomView, EmojiKeyboardListener, EmojiR
         }
     }
 
+    private fun hasCameraPermission(context: Context): Boolean {
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt]: I'd move this function here to `AndroidPermissionsHelper` class in order to centralize all the permissions stuffs. 

We could also move the `canWriteToExternalStorage()` and `checkWritingPermission()` from the `ImageHelper` class to `AndroidPermissionsHelper` - It can be done on other PR though.

**Review by philipbrito — CHANGES_REQUESTED** [review]

File: app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt (hunk 2 above)
Comment (divyanshub024) [reply app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt]: @filipedelimabrito I'll do both the things in this PR only.

**Comment by philipbrito** [comment]
@divyanshub024 Any news here? 
Thank you.

**Comment by divyanshub024** [comment]
@filipedelimabrito I have made the requested changes.

**Review by philipbrito — APPROVED** [review]
Thank you very much for sending this PR @divyanshub024!
