### PR TITLE
[FIX] Fixes issues and memory leaks after changing language

### LINKED ISSUE #2276: [BUG] Error while changing language
Your Rocket.Chat.Android version: 3.4.0 (2062)
Mobile device model: Xiaomi Redmi 3
OS version: Lineage OS, Android 7.1.2
Your Rocket.Chat Server version: 0.74.3

When changing the language, an error occurs:

### LINKED ISSUE #2323: [BUG] App stoped when click back after changed language
## To Reproduce

1. Go to language
2. Change any language
3. and try to close the app 
4. See error -->

## Expected behavior
user should be able to smoothly exit app without showing stoped .

## Devices and Versions

* Rocket.Chat.Android version: 3.4.1(2069)
* Rocket.Chat Server version: 1.1.0-develop

* Android version: 8.1.0 OPMI

## Additional context
https://youtu.be/xlsmoDp07tI

### LINKED ISSUE #2333: [BUG] App crashes when pressing back after changing the language
## Describe the bug
App crashes when pressing back button after changing the language from the settings.

## To Reproduce

1. Go to Settings.
2. Change language.
3. From the chats list, press back button on your device.
4. App will crash.

## Expected behavior

App should not crash.

## Logs

```
    --------- beginning of crash
2019-05-21 19:36:47.430 27117-27117/chat.rocket.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chat.rocket.android.dev, PID: 27117
    java.lang.IllegalStateException: Fragment already added: ChatRoomsFragment{98ea8a5 #0 id=0x7f0900ea ChatRoomsFragment}
        at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManager.java:1916)
        at androidx.fragment.app.BackStackRecord.executePopOps(BackStackRecord.java:828)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2622)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:884)
        at androidx.fragment.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:827)
        at androidx.fragment.app.FragmentActivity.onBackPressed(FragmentActivity.java:190)
        at android.app.Activity.onKeyUp(Activity.java:2727)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2704)
        at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:126)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:334)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4823)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4788)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4459)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4516)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4492)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4662)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2449)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2028)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2019)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2426)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:328)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
```

## GIF

Language Change Crash

## Devices and Versions
Rocket.Chat.Android version: 3.4.1 (2069)
Rocket.Chat Server version: 1.1.0-develop
Mobile device model and OS version: XPERIA XA Ultra - Android 7.0

### PR DESCRIPTION
**Pull request by hfeky**
@RocketChat/android

Closes #2276
Closes #2323
Closes #2333

#### Changes:

By examining the logs produced in #2333, there were issues when the activity gets recreated after changing the language. It turns out that fragments get recreated as well on activity recreation, and thus `SettingsFragment` and possibly other fragments' `onCreate()` were called, causing memory leaks and the issues reported above, even though they were not visible. To overcome these issues, one could use [`setRetainInstance(true)`](https://developer.android.com/reference/android/app/Fragment.html#setRetainInstance(boolean)) to all the created fragments to prevent the fragments from calling `onDestroy()` and `onCreate()` when the activity is recreated, but since this method does not work for fragments added to the back stack, as mentioned in the Developers Reference, this solution was not possible. So all I did was just finishing `MainActivity` and recreating it on language change, and it solved all these issues.

#### GIF for the change:

As you can see, `NullPointerException` no longer occurs, and no crash occurs anymore when pressing back button after changing the language.

language_change_fix

### CODE REVIEW

File: app/src/main/java/chat/rocket/android/directory/presentation/DirectoryPresenter.kt [hunk 1]
```diff
@@ -136,7 +136,7 @@ class DirectoryPresenter @Inject constructor(
         }
     }
 
-    fun tiDirectMessage(username: String, name: String) {
+    fun toDirectMessage(username: String, name: String) {
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/directory/presentation/DirectoryPresenter.kt:139]: Good 👀

**Review by philipbrito — APPROVED** [review]
👊
