### PR TITLE
[BUG] Resolves incorrect context issue in login activity

### LINKED ISSUE #656: [BUG] App crashes on pressing android back button from the login screen
- Rocket.Chat.Android app version: 1.1.0-DEBUG
- Device model (or emulator): HTC Desire 628
- Steps to reproduce:
1. After entering the server url, when the login screen appears and we press the android back button, the app crashes. 

@leonardoaramaki @rafaelks I am working on this one.

### PR DESCRIPTION
**Pull request by aniketsingh03**
@RocketChat/android

Closes #656 and #648 

It looked like an incorrect context was given to start add server url activity from login activity when back button is pressed. I fixed this bug by changing the context from that of the application to that of the LoginActivity.

See the context given here is the application's context.
https://github.com/RocketChat/Rocket.Chat.Android/blob/6f80a3c48e08b17ac6d8c088f394d45459800d89/app/src/main/java/chat/rocket/android/fragment/server_config/LoginPresenter.kt#L34-L43
@leonardoaramaki ^^

### CODE REVIEW

**Comment by aniketsingh03** [comment]
@leonardoaramaki you can review this!

**Comment by leonardoaramaki** [comment]
@aniketsingh03 Can you resolve the conflicts?

**Comment by aniketsingh03** [comment]
@leonardoaramaki I have resolved merge conflicts, you can merge once the checks are complete.

**Comment by aniketsingh03** [comment]
@leonardoaramaki I have fixed #648 also in this branch, please review and merge this.

File: app/src/main/java/chat/rocket/android/helper/BackStackHelper.java [hunk 1]
```diff
@@ -0,0 +1,9 @@
+package chat.rocket.android.helper;
+
+/**
+ * Created by whocares on 28/12/17.
+ */
+
```
Comment (leonardoaramaki) [inline app/src/main/java/chat/rocket/android/helper/BackStackHelper.java]: @aniketsingh03 Please always remove the `author` doc. It's not helpful at all and we can keep track of the changes everyone does by using git blame or anything like that.

File: app/src/main/java/chat/rocket/android/fragment/server_config/LoginContract.java [hunk 2]
```diff
@@ -23,13 +26,13 @@
 
         void showTwoStepAuth();
 
-        void goBack();
+        void goBack(Context ctx);
```
Comment (leonardoaramaki) [inline app/src/main/java/chat/rocket/android/fragment/server_config/LoginContract.java]: We don't need to pass a Context to a `view` implementation since they're supposed to be either an Activity or a Fragment and hence we can get a proper Activity Context from there.

File: app/src/main/java/chat/rocket/android/fragment/server_config/LoginContract.java [hunk 3]
```diff
@@ -23,13 +26,13 @@
...
     }
 
     interface Presenter extends BaseContract.Presenter<View> {
 
         void login(String username, String password);
 
-        void goBack();
+        void goBack(Context ctx);
```
Comment (leonardoaramaki) [inline app/src/main/java/chat/rocket/android/fragment/server_config/LoginContract.java:36]: Here's fine to have a Context as parameter since the presenter doesn't have a **direct** access to the view's implementation (would require an ugly casting). :+1:

**Review by leonardoaramaki — CHANGES_REQUESTED** [review]
@aniketsingh03 Nice catch on the correct Context thing. Your assumption was right. If we wanted to start a brand new Activity from an application's  context we should have set the flag `FLAG_ACTIVITY_NEW_TASK` which is not what we are doing here.
Please have a look on the comments I left on your PR.

File: app/src/main/java/chat/rocket/android/fragment/server_config/LoginFragment.kt [hunk 4]
```diff
@@ -160,8 +161,8 @@ class LoginFragment : AbstractServerConfigFragment(), LoginContract.View {
         presenter.release()
         super.onPause()
     }
-
-    override fun goBack() {
-        presenter.goBack()
+    override fun goBack(ctx: Context?) {
```
Comment (leonardoaramaki) [inline app/src/main/java/chat/rocket/android/fragment/server_config/LoginFragment.kt]: We need a newline above this.

**Comment by aniketsingh03** [comment]
@leonardoaramaki I have made the requested changes, you may merge it.

**Comment by aniketsingh03** [comment]
@leonardoaramaki ..

**Review by leonardoaramaki — COMMENTED** [review]
LGTM

**Review by leonardoaramaki — APPROVED** [review]
