### PR TITLE
[BUG] SaveInstanceState on orientation change

### LINKED ISSUE #1090: [BUG] Orientation change in settings reset the fragment to chats
Your Rocket.Chat.Android version:
- versionCode 2009
- versionName "2.0.0-rc1"

Mobile device model and OS version: Nexus 6 - Android 7.1

settings-rotation

### PR DESCRIPTION
**Pull request by divyanshub024**
@RocketChat/android

Closes #1090 #831 #824 
screen-rotate

### CODE REVIEW

**Comment by divyanshub024** [comment]
@rafaelks This PR is ready for review

File: app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt [hunk 1]
```diff
@@ -268,4 +269,14 @@ class MainActivity : AppCompatActivity(), MainView, HasActivityInjector, HasSupp
             }
         }
     }
+
+    override fun onSaveInstanceState(outState: Bundle?) {
+        super.onSaveInstanceState(outState)
+        outState?.putBoolean(CURRENT_STATE,isFragmentAdded)
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt:275]: There is only a need of adding a space after `,` here but we can fix it later.
Thanks for your PR @divyanshub024 !

**Review by philipbrito — APPROVED** [review]

File: app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt (hunk 1 above)
Comment (divyanshub024) [reply app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt:275]: ok, I'll fix that in next PR.
