### PR TITLE
[FIX] fix temporary status on reconnection

### LINKED ISSUE #1517: [BUG] Status presence is not getting recovered when the app reconnects in background
(as our discussion internally)

### PR DESCRIPTION
**Pull request by luciofm**
depends on https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/198

Closes #1517

### CODE REVIEW

File: app/src/main/java/chat/rocket/android/app/AppLifecycleObserver.kt [hunk 1]
```diff
@@ -31,14 +31,8 @@ class AppLifecycleObserver @Inject constructor(
...
         launch {
-            val currentServer = serverInteractor.get()
-            val account = currentServer?.let { getAccountInteractor.get(currentServer) }
-            val client = account?.let { factory.create(currentServer) }
-
-            try {
-                client?.setTemporaryStatus(userStatus)
-            } catch (exception: RocketChatException) {
-                Timber.e(exception)
+            serverInteractor.get()?.let { currentServer ->
```
Comment (philipbrito) [inline app/src/main/java/chat/rocket/android/app/AppLifecycleObserver.kt:34]: Great!

**Review by philipbrito — APPROVED** [review]

File: app/src/main/java/chat/rocket/android/app/AppLifecycleObserver.kt (hunk 1 above)
Comment (philipbrito) [reply app/src/main/java/chat/rocket/android/app/AppLifecycleObserver.kt:34]: @luciofm You could leave the `currentServer ->` since it is a simple code (`it` is explicitly here- even more by declarating `serverInteractor.get()`).
